 CREATE TABLE WorkItem ( 
    WorkItem_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TaskTitle VARCHAR(50) NOT NULL,
	TaskDescription VARCHAR(8000) NULL,
    Complete INTEGER NOT NULL DEFAULT 0, 
    CreationDateTime DATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP),
	DeletionDateTime DATETIME NULL
);



